Add product and pricing operations, as well as frontend views
melinaschweizer/provman pull request #2
Opened 2021-08-25 13:16 UTC by dooreaga

2021-08-29 16:48 UTC, melinaschweizer requested changes

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/controller/MyController.java
> +		return "pricings";
could we name this jsp princingList?

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/controller/MyController.java
> +		return "pricings";
could we rename pricings as princingList?

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/controller/MyController.java
> +		return "products";
could we rename products as productList?

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/model/ProductPricing.java
> +@Table(name = "pricings")
this table should be renamed "pricing" (no S)

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/model/ProductPricing.java
> +  @ManyToOne
This column would've been a primary key had we not used Hibernate, it should be defined right after primary key

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/model/Provider.java
> +	@Column(name = "code", unique=true, nullable = false)
do we need this column?

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/scripts/db_init.sql
> +create table products (
please use just 'product' to follow convention ( tables already imply there will be many rows)

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/scripts/db_init.sql
> +create table pricings (
please use just 'pricing'

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/webapp/WEB-INF/views/pricings.jsp
> +<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
please rename jsp to pricingList.jsp

2021-08-29 16:48 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/controller/MyController.java
> +	public String updateProduct(@Valid ProductAndPrice productAndPrice, ModelMap modelMap) {
not entirely sure I understand how the product and pricing objs get filled.. maybe we can chat about this?

2021-09-01 07:52 UTC, dooreaga commented on src/main/java/com/myfarmer/provman/model/ProductPricing.java
> +  @ManyToOne
Not sure I get what you mean by this? Are you talking about this foreign key constraint on the product table?

2021-09-01 07:53 UTC, dooreaga commented on src/main/java/com/myfarmer/provman/model/Provider.java
> +	@Column(name = "code", unique=true, nullable = false)
This was from your initial commit to the repo, it looks like you use it to retrieve the providers?

2021-09-01 14:12 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/model/Provider.java
> +	@Column(name = "code", unique=true, nullable = false)
yes, it was from the demo.. but I don't think it's necessary for our app, it can be deleted (not a showstopper, wecan do it later)

2021-09-01 14:13 UTC, melinaschweizer commented on src/main/java/com/myfarmer/provman/model/ProductPricing.java
> +  @ManyToOne
sorry, I meant putting the column further up in the code, in 2nd place if I recall correctly. It's an important column, so it should show up close to the top (not a showstopper, can do later)

2021-09-02 14:24 UTC, merged