Unittesting
melinaschweizer/provman pull request #6
Opened 2021-09-22 10:54 UTC by melinaschweizer

2021-09-22 14:46 UTC, dooreaga requested changes

2021-09-22 14:46 UTC, dooreaga commented on app/src/test/java/com/myfarmer/provman/ProviderServiceImplTest.java
> +		boolean retVal = service.isProviderCodeUnique(2, "a");
From reading the documentation on checking for unique values, it looks like a HibernateException should occur in the case that the value used to search is not unique

2021-09-23 11:41 UTC, melinaschweizer commented on app/src/test/java/com/myfarmer/provman/ProviderServiceImplTest.java
> +	void testFindById() {
I wondered the same, but a lot of these are just tests for correctness, and in case of future changes/upgrades.

2021-09-23 11:48 UTC, melinaschweizer commented on app/src/main/java/com/myfarmer/provman/service/ProviderServiceImpl.java
yeah, i saw this, made a mental note, and then forgot about it. I uncommented the line.

2021-09-23 11:53 UTC, melinaschweizer commented on app/src/test/java/com/myfarmer/provman/ProviderServiceImplTest.java
> +		boolean retVal = service.isProviderCodeUnique(1, "a");
the check on whether it's the same or not just compares the Id field (which is 1), it doesn't compare against the "a".. so the test should be good

2021-09-23 12:23 UTC, melinaschweizer commented on app/src/test/java/com/myfarmer/provman/ProviderServiceImplTest.java
> +		boolean retVal = service.isProviderCodeUnique(2, "a");
good point! changed test to throw and assert HibernateException

2021-09-23 13:22 UTC, melinaschweizer commented on app/src/test/java/com/myfarmer/provman/controller/ProvmanControllerTest.java
> +		Mockito.when(providerService.isProviderCodeUnique(Mockito.any(), Mockito.any())).thenReturn(false);
The exception would occur if there were 2 entries in the DB with the same code. In this case though, I'm just checking that there isn't one entry in the DB with the same code but different ID, in other words, that another entry with the same code doesn't exist. If it does, isProviderCodeUnique would just return false.

2021-09-23 13:23 UTC, melinaschweizer commented on app/src/main/java/com/myfarmer/provman/model/Provider.java
> +@AllArgsConstructor
Without it, the unit test fails.

2021-09-23 15:48 UTC, dooreaga commented on app/src/main/java/com/myfarmer/provman/service/ProviderServiceImpl.java
Gotcha sounds good, yeah I was curious what the method was doing lol

2021-09-23 15:50 UTC, dooreaga commented on app/src/test/java/com/myfarmer/provman/ProviderServiceImplTest.java
> +		boolean retVal = service.isProviderCodeUnique(1, "a");
Yeah, I don't think the test will fail ever because the call is being mocked anyways. I was just a bit thrown off seeing that after reading what the method did

2021-09-23 15:51 UTC, dooreaga commented on app/src/test/java/com/myfarmer/provman/ProviderServiceImplTest.java
> +		boolean retVal = service.isProviderCodeUnique(2, "a");
Ahh ok maybe the wording of the function threw me off, I thought it was supposed to be checking whether there were multiple providers with the same code but different id's in the database

2021-09-23 15:52 UTC, dooreaga approved these changes

2021-09-24 08:19 UTC, merged